version: "3.9"
services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --init-file /docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "the_company_db"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 25s
      retries: 3
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
  api:
    build: .
    command: /companies-api/companies-api
    ports:
      - "8080:8080"
    environment:
      MYSQL_DSN: root:password@tcp(mysql:3306)/the_company_db?parseTime=true&sql_mode=NO_ZERO_DATE
    volumes:
      - .:/companies-api
    depends_on:
      - mysql

networks:
  default:
    name: companies-stack
    driver: overlay
    attachable: true